spring:
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:file:./data/filedb
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: never
  config:
    use-legacy-processing: true
  h2:
    console:
      enabled: true

server:
  port: 8080
  include-debug-info: true
  error:
    include-message: always


